name: Listeleri Güncelleyelim

on:
  schedule:
    - cron: '0 */2 * * *'  # Her 2 saatte bir calistir
  workflow_dispatch:  # Manuel tetiklemeye izin verip istediğimiz zaman Action altından Run Workflow diyerek de calistirmayi saglayabiliriz.

permissions:
  contents: write

jobs:
  kanal-guncelleme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Gereklilikleri Yukle
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Kanal Listelerini Isle
        run: |
          python .github/scripts/process_channels.py
          
      - name: Degisiklikleri Kaydet ve Gonder
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull origin main
          git add kekik-vavoo/*.m3u huhu/*.m3u kool/*.m3u oha/*.m3u
          git diff --quiet && git diff --staged --quiet || git commit -m "Tüm listeleri guncelledik"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}