name: Kanal Listelerini Guncelle

on:
  schedule:
    - cron: '0 */6 * * *'  # Her 6 saatte bir calistir
  workflow_dispatch:  # Manuel tetiklemeye izin ver

jobs:
  kanal-guncelleme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Gereklilikleri Yukle
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Kanal Listelerini Isle
        run: |
          python .github/scripts/process_channels.py
          
      - name: Degisiklikleri Kaydet ve Gonder
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git pull --rebase origin main
          git add -f kekik-vavoo/
          git add *.m3u
          git diff --quiet && git diff --staged --quiet || git commit -m "Kanal listelerini guncelledik"
          git push origin main